#!/bin/sh
# https://manpages.debian.org/testing/live-build/lb_clean.1.en.html

set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
